[package]
name = "cviz"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 WITH LLVM-exception"

[dependencies]
clap = { version = "4", features = ["derive"] }
wasmparser = { version = "0.244", features = ["component-model"] }
anyhow = "1.0"

[dev-dependencies]
wat = "1"
